# Site settings
title: "Gopal Iyer"
description: "Gopal Iyer's Personal CV Page"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Gopal Iyer, Ph.D."
resume_title:                   "Product Security Leader"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "iyergkris [at] gmail [dot] com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "-"
resume_contact_address:         "Fremont, CA"

resume_header_contact_info:     "Fremont, CA • iyergkris [at] gmail [dot] com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Cybersecurity leader with a proven history of building and managing successful teams in the automotive and medical device industries.  Expertise in embedded systems security, zero-day defenses, and cryptography.  Adept at developing and implementing robust security solutions.  Inventor with multiple patents and publications, demonstrating a commitment to innovation and thought leadership in the field.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_patents:         true
resume_section_pubs:            true
resume_section_links:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/iyergkris"
  resume_twitter_url:           "http://twitter.com/iyergkris"
  resume_linkedin_url:          "https://www.linkedin.com/in/iyer-gopal"
  resume_instagram_url:         "https://www.instagram.com/iyergkris/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
